// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using DevExtreme.AspNet.Data.ResponseModel;
using DevExtreme.AspNet.Mvc;
using Sample.CustomerService.Customers;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Sample.CustomerService.Customers;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ICustomerAppService), typeof(CustomerClientProxy))]
public partial class CustomerClientProxy : ClientProxyBase<ICustomerAppService>, ICustomerAppService
{
    public virtual async Task<LoadResult> GetBasicListAsync(DataSourceLoadOptions loadOptions)
    {
        return await RequestAsync<LoadResult>(nameof(GetBasicListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataSourceLoadOptions), loadOptions }
        });
    }

    public virtual async Task<BasicCustomerDto> GetByIdAsync(int customerID)
    {
        return await RequestAsync<BasicCustomerDto>(nameof(GetByIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(int), customerID }
        });
    }
}
